name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Créer fichier .env
        run: |
          echo "MYSQL_HOST=${{secrets.MYSQL_HOST}}" >> .env
          echo "MONGODB_HOST=${{secrets.MONGODB_HOST}}" >> .env
          echo "MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}" >> .env
          echo "MYSQL_USER=${{secrets.MYSQL_USER}}" >> .env
          echo "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_INITDB_ROOT_USERNAME}}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_INITDB_ROOT_PASSWORD}}" >> .env
          echo "MONGODB_HOST=${{secrets.MONGODB_HOST}}" >> .env
          echo "MONGODB_PORT=${{secrets.MONGODB_PORT}}" >> .env
          echo "MONGO_USER=${{secrets.MONGO_USER}}" >> .env
          echo "MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}}" >> .env
          echo "MONGO_DB=${{secrets.MONGO_DB}}" >> .env

      - name: Démarrer le conteneur
        run: |
          docker network create labo01-network
          docker compose up -d

      - name: Attendre MySQL
        run: |
          sleep 10
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done
          sleep 5

      - name: Éxécuter les tests (TODO - ajouter test_products)
        run: 
         docker exec store_manager_cli pytest ./src/tests/test_user.py
         docker exec store_manager_cli pytest ./src/tests/test_product.py

      - name: Déploiement de l'application
        if: success()  
        run: 
          git reset --hard
          git clean -fd
          git pull origin main
          docker compose down -v
          docker compose up -d --build

      - name: Cleanup
        if: always()
        run: docker compose down -v
